package com.cricket;

public class Sorted {
    public enum SortByField {

        AVERAGE,STRIKE_RATE,TOTAL_SIX_AND_FOUR,BEST_STRIKE_WITH_TOTAL_SIX_AND_FOUR,AVERAGE_WITH_STRIKE_RATE,
        MAX_RUN_WITH_BEST_AVG,BEST_BOWLER_AVERAGE,TOP_BOWLERS_STRIKE_RATE,BEST_ECONOMY_RATE,BEST_STRIKING_RATE_WITH_5W_AND_4W,
        BEST_BOWLING_AVERAGE_WITH_STRIKE_RATE,MAXIMUM_WICKETS_WITH_BEST_AVERAGE_RATE, BEST_BATTING_BOWLING_AVERAGE,ALL_ROUNDER_PLAYER

    }
}
